version: '3.8'

networks:
  loki:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  node_exporter:
    image: prom/node-exporter:latest
    hostname: node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - '9100:9100'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - '9090:9090'
    networks:
      - monitoring

  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.8.3
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    container_name: promtail
    hostname: promtail
    image: grafana/promtail:2.8.3
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command:
      - '--config.file=/etc/promtail/config.yml'
      - '--config.expand-env=true'
    depends_on:
      - loki
    networks:
      - loki

  grafana:
    container_name: grafana
    hostname: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    env_file: ./grafana/config.monitoring
    entrypoint:
      - sh
      - -euc
      - /run.sh
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - loki
      - monitoring
